server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/member?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root@123

mybatis:
  mapperLocation: classpath:mapper/*.xml
  type-aliase-package: com.atguigu.springcloud.entities
