server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.55.93:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    validationQuery: SELECT 1

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
logging:
  level:
    com.atguigu.springcloud: DEBUG
