spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          配置git仓库地址
          uri: https://github.com/ObedWang/config
#          配置仓库路径
#          search-paths: spring-cloud.yml
#          仓库分支
          default-label: main
#          git仓库用户名
          username:
#            git的密码
          password:

server:
  port: 8888